### PR TITLE
Add ubuntu 20.04

### PR DESCRIPTION
**Pull request by hungrymonkey**
I made a simple pr request. What is a simple way to test my changes?

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

### CODE REVIEW

**Comment by hungrymonkey** [comment]
```
$ molecule test

---

dependency:

  name: galaxy

driver:

  name: docker

lint:

  enabled: true

  name: yamllint

  options:

    config-file: molecule/default/yaml-lint.yml

platforms:

  - command: ${MOLECULE_DOCKER_COMMAND:-""}

    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest

    name: ${ROLE_NAME}-${MOLECULE_DISTRO:-centos7}

    pre_build_image: true

    privileged: true

    volumes:

      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      - /var/lib/docker

provisioner:

  lint:

    name: ansible-lint

  name: ansible

  playbooks:

    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}

scenario:

  name: default

verifier:

  lint:

    name: flake8

  name: testinfra

ERROR: Failed to pre-validate.

{'lint': ['must be of string type']}

The command "molecule test" exited with 1.
```

**Comment by hungrymonkey** [comment]
https://github.com/ansible-community/molecule/issues/2560#issuecomment-589147529

**Comment by hispanico** [comment]
We need to migrate from molecule v2 to molecule v3

**Comment by hispanico** [comment]
I've update the molecule configuration to molecule ve.
If you merge my latest change on your branch you should be able to test Ubuntu 20.04

**Comment by hungrymonkey** [comment]
Ok, Let me take some times to try to merge your work and add my changes to the end

**Comment by hungrymonkey** [comment]
Opp, I think I completely mess up my commit. Oh well.

**Pull request closed without merging**
